server:
  port: 8080

spring:
  application:
    name: ptm-backend

  #datasource:
  #  url: jdbc:mysql://localhost:3306/crud_app?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  #  username: root
  #  password: root
  #  driver-class-name: com.mysql.cj.jdbc.Driver


  h2:
    console:
      enabled: true # Enables the H2 web console
      path: /h2-console # Configures the console access path (e.g., http://localhost:8080/h2-console)
  datasource:
    url: jdbc:h2:mem:testdb # JDBC URL for an in-memory database named 'testdb'
    driver-class-name: org.h2.Driver
    username: sa # Default H2 username
    password: password # Default H2 password (can be left blank)
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect # Specifies the H2 dialect for Hibernate
    hibernate:
      ddl-auto: update # Automatically updates the database schema when the app starts
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true


  sql:
    init:
      mode: always
